apiVersion: v1
kind: ConfigMap
metadata:
  name: vlan-api-config
  labels:
    app: vlan-api
data:
  # Application configuration
  API_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  DATA_FILE_PATH: "/app/data/vlans.json"
  
  # Health check configuration
  HEALTH_CHECK_TIMEOUT: "30"