apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlan-api-deployment
  labels:
    app: vlan-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlan-api
  template:
    metadata:
      labels:
        app: vlan-api
        version: v1
    spec:
      containers:
      - name: vlan-api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: vlan-api-config
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: data-storage
          mountPath: /app/data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: vlan-api-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vlan-api-pvc
  labels:
    app: vlan-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard