apiVersion: v1
kind: Service
metadata:
  name: vlan-api-service
  labels:
    app: vlan-api
spec:
  type: LoadBalancer
  selector:
    app: vlan-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: vlan-api-service-internal
  labels:
    app: vlan-api
spec:
  type: ClusterIP
  selector:
    app: vlan-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP